[project]
name = "mazegen"
version = "1.0.0"
description = "A lightweight procedural maze generator built in Python for the 42 curriculum"
readme = "README.md"
authors = [
    {name = "labdalla"},
    {name = "naldibis"},
]
license = "MIT"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"
keywords = ["maze", "generator", "procedural", "42"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Games/Entertainment",
    "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/LaithAbdallah/42-Amazing"

[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["maze_generation"]
